import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";
import { muiTheme } from "../muiTheme";
import { Box, Typography } from "@mui/material"
import { styled } from '@mui/material/styles';
import ButtonBase from '@mui/material/ButtonBase';
import { useNavigate } from 'react-router-dom'

const inter = Inter({ subsets: ["latin"] });

const img1_url = "https://media.istockphoto.com/id/1371441366/photo/colorful-psychedelic-rainbow-swirls-background.jpg?b=1&s=170667a&w=0&k=20&c=NWw28oh1tVRrWlBaj3j5WBmKnwUCr9BggHeVVKSdS50=";
const img2_url = "https://static01.nyt.com/images/2023/02/21/well/10-WELL-PSYCHEDELICS-CONCERNS/10-WELL-PSYCHEDELICS-CONCERNS-mediumSquareAt3X.jpg";

const ImageButton = styled(ButtonBase)(({ theme }) => ({
  position: 'relative',
  height: 200,
  [theme.breakpoints.down('sm')]: {
    width: '100% !important', // Overrides inline-style
    height: 100,
  },
  '&:hover, &.Mui-focusVisible': {
    zIndex: 1,
    '& .MuiImageBackdrop-root': {
      opacity: 0.15,
    },
    '& .MuiImageMarked-root': {
      opacity: 0,
    },
    '& .MuiTypography-root': {
      border: '4px solid currentColor',
    },
  },
}));

const ImageSrc = styled('span')({
  position: 'absolute',
  left: 0,
  right: 0,
  top: 0,
  bottom: 0,
  backgroundSize: 'cover',
  backgroundPosition: 'center 40%',
});

const Image = styled('span')(({ theme }) => ({
  position: 'absolute',
  left: 0,
  right: 0,
  top: 0,
  bottom: 0,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  color: theme.palette.common.white,
}));

const ImageBackdrop = styled('span')(({ theme }) => ({
  position: 'absolute',
  left: 0,
  right: 0,
  top: 0,
  bottom: 0,
  backgroundColor: theme.palette.common.black,
  opacity: 0.4,
  transition: theme.transitions.create('opacity'),
}));

const ImageMarked = styled('span')(({ theme }) => ({
  height: 3,
  width: 18,
  backgroundColor: theme.palette.common.white,
  position: 'absolute',
  bottom: -2,
  left: 'calc(50% - 9px)',
  transition: theme.transitions.create('opacity'),
}));

function Home()
{
  let navigate;
  if(typeof document !== 'undefined')
  {
    navigate = useNavigate();
  }
  return (
    <div>
    <main className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={muiTheme}>
        <Box justifyContent='center' sx={{display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '50px'}}>
          <Typography variant='h1' sx={{fontWeight: 'bold', alignSelf: 'center', color: 'rgba(0, 0, 0, 255)'}}>
            Bored?
          </Typography>
          <Box sx={{display: 'flex', flexDirection: 'row', alignItems: 'flex-start'}}>
            <Box sx={{display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
              <Typography variant='h2' sx={{fontWeight: 'regular', width: '500px', color: 'rgba(0, 0, 0, 255)'}}>
                Tired of doing Project 3 with Smallberg?
              </Typography>
            </Box>
            <Box sx={{display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '40px'}}>

              <ImageButton focusRipple key={'personalRec'} style={{width: '700px', height: '150px'}} onClick={() => {
                if (navigate != null)
                  navigate('first-post');
              }}>
                <ImageSrc style={{ backgroundImage: `url(${img1_url})` }} />
                <ImageBackdrop className="MuiImageBackdrop-root" />
                <Image>
                  <Typography variant='h4' component="span" color="inherit" sx={{position: 'relative', p: 4, pt: 2, 
                    pb: (theme) => `calc(${theme.spacing(1)} + 6px)`}}>
                    Get a Personal Recommendation
                    <ImageMarked className="MuiImageMarked-root" />
                  </Typography>
                </Image>
                
              </ImageButton>

              <ImageButton focusRipple key={'personalRec'} style={{width: '700px', height: '150px'}} onClick={() => {
                
              }}>
                <ImageSrc style={{ backgroundImage: `url("${img2_url}")` }} />
                <ImageBackdrop className="MuiImageBackdrop-root" />
                <Image>
                  <Typography variant='h4' component="span" color="inherit" sx={{position: 'relative', p: 4, pt: 2, 
                    pb: (theme) => `calc(${theme.spacing(1)} + 6px)`}}>
                    Advertise Your Place Here
                    <ImageMarked className="MuiImageMarked-root" />
                  </Typography>
                </Image>
                
              </ImageButton>

            </Box>
          </Box>
        </Box>
        </ThemeProvider>
      
    
    </main>
    </div>
  );
  /*
    <p className={inter.className}>
            <Link href="/posts/first-post">Read this page!</Link>
          </p>
  */
 //}
}

export default Home;